### ISSUE TITLE
How to aggregate global statistics?

### ISSUE THREAD

**Issue by chrisngyn** [chrisngyn/fellowship-class-profile#28]
When a user logs in, we'll generate their statistics by just pulling from our database.

Global statistics on the other hand, are something else. We kind of have "two" kinds of global statistics, if you will.

One type is stats that aren't tied to any user. For example, number of repos in the MLH-Fellowship organization, and their dominant languages. The other kind of stat is the summation of all Fellows' statistics.

Ideas on how to store global stats? I was thinking we store run the files to generate the stats, store all the global stats in our database and constantly update it at midnight.

For example, I can run some of the files (i.e. `org_repo_stats.py`) and get a language dominant frequency dictionary, and throw that into our database. Have this happen every midnight.

I can run `most_active_day.py` and get my most active day and week for my own account, store this under my GitHub ID in the database, but also update the global stat of this as well at the same time. Have this happen every midnight.

Kind of confused at how we should approach this, so let's discuss the best way to implement.

**Comment by kbanc** [comment]
I was thinking after the `repositories` and `users_info` tables are loaded, we can run a couple of queries to calculate the global stats from there.

We can then store the combination of stats in another db table. I'll update the schemas in our google doc to make a `global_stats` table. 

I also think, at least for the duration of the program, we should have a chronjob running at night to update the db (we can let users know about the downtime on the site or something).
